DROP TABLE IF EXISTS downloads;
DROP TABLE IF EXISTS magnets;
DROP TABLE IF EXISTS pages;
DROP TABLE IF EXISTS profile_priorities;
DROP TABLE IF EXISTS episodes;
DROP TABLE IF EXISTS seasons;
DROP TABLE IF EXISTS medias;
