// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

type Episode struct {
	ID            int64  `json:"id"`
	SeasonID      int64  `json:"season_id"`
	EpisodeNumber int64  `json:"episode_number"`
	AirDate       string `json:"air_date"`
	Status        string `json:"status"`
}

type Medium struct {
	ID         int64  `json:"id"`
	TmdbID     int64  `json:"tmdb_id"`
	Type       string `json:"type"`
	Title      string `json:"title"`
	AirDate    string `json:"air_date"`
	PosterPath string `json:"poster_path"`
}

type Season struct {
	ID           int64  `json:"id"`
	SeriesID     int64  `json:"series_id"`
	SeasonNumber int64  `json:"season_number"`
	EpisodeCount int64  `json:"episode_count"`
	AirDate      string `json:"air_date"`
	PosterPath   string `json:"poster_path"`
}
