// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"time"
)

type Episode struct {
	ID            int64      `json:"id"`
	SeasonID      int64      `json:"season_id"`
	EpisodeNumber int64      `json:"episode_number"`
	AirDate       *time.Time `json:"air_date"`
	Status        string     `json:"status"`
}

type Medium struct {
	ID         int64      `json:"id"`
	TmdbID     int64      `json:"tmdb_id"`
	Type       string     `json:"type"`
	Title      string     `json:"title"`
	AirDate    *time.Time `json:"air_date"`
	PosterPath string     `json:"poster_path"`
	Status     string     `json:"status"`
}

type Resource struct {
	ID         int64   `json:"id"`
	MediaID    int64   `json:"media_id"`
	SeasonID   *int64  `json:"season_id"`
	EpisodeID  *int64  `json:"episode_id"`
	MagnetUrl  string  `json:"magnet_url"`
	Seeders    int64   `json:"seeders"`
	IsChinese  int64   `json:"is_chinese"`
	Resolution *string `json:"resolution"`
	Status     string  `json:"status"`
}

type Season struct {
	ID           int64      `json:"id"`
	SeriesID     int64      `json:"series_id"`
	SeasonNumber int64      `json:"season_number"`
	EpisodeCount int64      `json:"episode_count"`
	AirDate      *time.Time `json:"air_date"`
	PosterPath   string     `json:"poster_path"`
}
