// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"time"
)

type Download struct {
	ID       int64   `json:"id"`
	MagnetID int64   `json:"magnet_id"`
	QbHash   *string `json:"qb_hash"`
	Error    *string `json:"error"`
	Status   string  `json:"status"`
}

type Episode struct {
	ID            int64     `json:"id"`
	SeasonID      int64     `json:"season_id"`
	EpisodeNumber int64     `json:"episode_number"`
	AirDate       time.Time `json:"air_date"`
	Status        string    `json:"status"`
}

type Magnet struct {
	ID        int64   `json:"id"`
	MediaID   int64   `json:"media_id"`
	SeasonID  *int64  `json:"season_id"`
	Title     string  `json:"title"`
	MagnetUrl string  `json:"magnet_url"`
	SizeMb    float64 `json:"size_mb"`
	Seeder    int64   `json:"seeder"`
	Profile   string  `json:"profile"`
	Status    string  `json:"status"`
}

type MagnetEpisode struct {
	MagnetID  int64 `json:"magnet_id"`
	EpisodeID int64 `json:"episode_id"`
}

type Media struct {
	ID         int64     `json:"id"`
	TmdbID     int64     `json:"tmdb_id"`
	Type       string    `json:"type"`
	Title      string    `json:"title"`
	AirDate    time.Time `json:"air_date"`
	PosterPath string    `json:"poster_path"`
	Status     string    `json:"status"`
}

type Page struct {
	ID         int64  `json:"id"`
	Provider   string `json:"provider"`
	MediaID    int64  `json:"media_id"`
	SeasonID   *int64 `json:"season_id"`
	DetailPath string `json:"detail_path"`
}

type ProfilePriority struct {
	Profile  string `json:"profile"`
	Priority int64  `json:"priority"`
}

type Season struct {
	ID           int64     `json:"id"`
	SeriesID     int64     `json:"series_id"`
	SeasonNumber int64     `json:"season_number"`
	EpisodeCount int64     `json:"episode_count"`
	AirDate      time.Time `json:"air_date"`
	PosterPath   string    `json:"poster_path"`
}
