// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repo

import (
	"context"
)

const countEpisodes = `-- name: CountEpisodes :one
SELECT COUNT(*) FROM episodes
WHERE season_id IN (SELECT id FROM seasons WHERE series_id = ?1 AND season_number = ?2)
`

type CountEpisodesParams struct {
	SeriesID     int64 `json:"series_id"`
	SeasonNumber int64 `json:"season_number"`
}

func (q *Queries) CountEpisodes(ctx context.Context, arg CountEpisodesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEpisodes, arg.SeriesID, arg.SeasonNumber)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMediaID = `-- name: GetMediaID :one
SELECT id FROM media WHERE tmdb_id = ?1
`

func (q *Queries) GetMediaID(ctx context.Context, tmdbID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMediaID, tmdbID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getPendingEpisodes = `-- name: GetPendingEpisodes :many
SELECT e.id, e.season_id, e.episode_number, e.air_date, e.status,
       s.season_number, s.series_id
FROM episodes e
JOIN seasons s ON e.season_id = s.id
WHERE e.air_date <= date('now')
  AND e.status = 'pending'
ORDER BY e.air_date ASC
`

type GetPendingEpisodesRow struct {
	ID            int64  `json:"id"`
	SeasonID      int64  `json:"season_id"`
	EpisodeNumber int64  `json:"episode_number"`
	AirDate       string `json:"air_date"`
	Status        string `json:"status"`
	SeasonNumber  int64  `json:"season_number"`
	SeriesID      int64  `json:"series_id"`
}

func (q *Queries) GetPendingEpisodes(ctx context.Context) ([]GetPendingEpisodesRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingEpisodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingEpisodesRow
	for rows.Next() {
		var i GetPendingEpisodesRow
		if err := rows.Scan(
			&i.ID,
			&i.SeasonID,
			&i.EpisodeNumber,
			&i.AirDate,
			&i.Status,
			&i.SeasonNumber,
			&i.SeriesID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeasonID = `-- name: GetSeasonID :one
SELECT id FROM seasons WHERE series_id = ?1 AND season_number = ?2
`

type GetSeasonIDParams struct {
	SeriesID     int64 `json:"series_id"`
	SeasonNumber int64 `json:"season_number"`
}

func (q *Queries) GetSeasonID(ctx context.Context, arg GetSeasonIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSeasonID, arg.SeriesID, arg.SeasonNumber)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getTVMedia = `-- name: GetTVMedia :many
SELECT id, tmdb_id FROM media WHERE type IN ('tv', 'anime')
`

type GetTVMediaRow struct {
	ID     int64 `json:"id"`
	TmdbID int64 `json:"tmdb_id"`
}

func (q *Queries) GetTVMedia(ctx context.Context) ([]GetTVMediaRow, error) {
	rows, err := q.db.QueryContext(ctx, getTVMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTVMediaRow
	for rows.Next() {
		var i GetTVMediaRow
		if err := rows.Scan(&i.ID, &i.TmdbID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEpisodeDownloaded = `-- name: MarkEpisodeDownloaded :exec
UPDATE episodes SET status = 'downloaded' WHERE id = ?1
`

func (q *Queries) MarkEpisodeDownloaded(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markEpisodeDownloaded, id)
	return err
}

const upsertEpisode = `-- name: UpsertEpisode :execrows
INSERT INTO episodes (season_id, episode_number, air_date, status)
VALUES (?1, ?2, ?3, 'pending')
ON CONFLICT(season_id, episode_number) DO UPDATE SET
    air_date = excluded.air_date
`

type UpsertEpisodeParams struct {
	SeasonID      int64  `json:"season_id"`
	EpisodeNumber int64  `json:"episode_number"`
	AirDate       string `json:"air_date"`
}

func (q *Queries) UpsertEpisode(ctx context.Context, arg UpsertEpisodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertEpisode, arg.SeasonID, arg.EpisodeNumber, arg.AirDate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertMedia = `-- name: UpsertMedia :execrows
INSERT INTO media (tmdb_id, type, title, air_date, poster_path)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT(tmdb_id) DO UPDATE SET
    type       = excluded.type,
    title      = excluded.title,
    air_date   = excluded.air_date,
    poster_path = excluded.poster_path
`

type UpsertMediaParams struct {
	TmdbID     int64  `json:"tmdb_id"`
	Type       string `json:"type"`
	Title      string `json:"title"`
	AirDate    string `json:"air_date"`
	PosterPath string `json:"poster_path"`
}

func (q *Queries) UpsertMedia(ctx context.Context, arg UpsertMediaParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertMedia,
		arg.TmdbID,
		arg.Type,
		arg.Title,
		arg.AirDate,
		arg.PosterPath,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertSeason = `-- name: UpsertSeason :execrows
INSERT INTO seasons (series_id, season_number, episode_count, air_date, poster_path)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT(series_id, season_number) DO UPDATE SET
    episode_count = excluded.episode_count,
    air_date      = excluded.air_date,
    poster_path   = excluded.poster_path
`

type UpsertSeasonParams struct {
	SeriesID     int64  `json:"series_id"`
	SeasonNumber int64  `json:"season_number"`
	EpisodeCount int64  `json:"episode_count"`
	AirDate      string `json:"air_date"`
	PosterPath   string `json:"poster_path"`
}

func (q *Queries) UpsertSeason(ctx context.Context, arg UpsertSeasonParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertSeason,
		arg.SeriesID,
		arg.SeasonNumber,
		arg.EpisodeCount,
		arg.AirDate,
		arg.PosterPath,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
