// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package repo

import (
	"context"
	"time"
)

const getOutOfSyncSeasons = `-- name: GetOutOfSyncSeasons :many
SELECT m.tmdb_id, s.id, s.season_number
FROM seasons s
JOIN media m ON m.id = s.series_id
WHERE
  m.type IN ('tv', 'anime')
  AND m.status IN ('wanted', 'monitoring')
  AND s.episode_count > (
    SELECT COUNT(*) FROM episodes e WHERE e.season_id = s.id
  )
`

type GetOutOfSyncSeasonsRow struct {
	TmdbID       int64 `json:"tmdb_id"`
	ID           int64 `json:"id"`
	SeasonNumber int64 `json:"season_number"`
}

func (q *Queries) GetOutOfSyncSeasons(ctx context.Context) ([]GetOutOfSyncSeasonsRow, error) {
	rows, err := q.db.QueryContext(ctx, getOutOfSyncSeasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOutOfSyncSeasonsRow
	for rows.Next() {
		var i GetOutOfSyncSeasonsRow
		if err := rows.Scan(&i.TmdbID, &i.ID, &i.SeasonNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutOfSyncTVs = `-- name: GetOutOfSyncTVs :many
SELECT id, tmdb_id
FROM media
WHERE
  type IN ('tv', 'anime')
  AND status IN ('wanted', 'monitoring')
`

type GetOutOfSyncTVsRow struct {
	ID     int64 `json:"id"`
	TmdbID int64 `json:"tmdb_id"`
}

func (q *Queries) GetOutOfSyncTVs(ctx context.Context) ([]GetOutOfSyncTVsRow, error) {
	rows, err := q.db.QueryContext(ctx, getOutOfSyncTVs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOutOfSyncTVsRow
	for rows.Next() {
		var i GetOutOfSyncTVsRow
		if err := rows.Scan(&i.ID, &i.TmdbID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEpisode = `-- name: UpsertEpisode :execrows
INSERT INTO episodes (season_id, episode_number, air_date)
VALUES (?1, ?2, ?3)
ON CONFLICT(season_id, episode_number) DO UPDATE SET
    air_date = excluded.air_date
`

type UpsertEpisodeParams struct {
	SeasonID      int64      `json:"season_id"`
	EpisodeNumber int64      `json:"episode_number"`
	AirDate       *time.Time `json:"air_date"`
}

func (q *Queries) UpsertEpisode(ctx context.Context, arg UpsertEpisodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertEpisode, arg.SeasonID, arg.EpisodeNumber, arg.AirDate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertMedia = `-- name: UpsertMedia :execrows
INSERT INTO media (tmdb_id, type, title, air_date, poster_path)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT(tmdb_id) DO UPDATE SET
  title = excluded.title,
  air_date = excluded.air_date,
  poster_path = excluded.poster_path
`

type UpsertMediaParams struct {
	TmdbID     int64      `json:"tmdb_id"`
	Type       string     `json:"type"`
	Title      string     `json:"title"`
	AirDate    *time.Time `json:"air_date"`
	PosterPath string     `json:"poster_path"`
}

func (q *Queries) UpsertMedia(ctx context.Context, arg UpsertMediaParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertMedia,
		arg.TmdbID,
		arg.Type,
		arg.Title,
		arg.AirDate,
		arg.PosterPath,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertSeason = `-- name: UpsertSeason :execrows
INSERT INTO seasons (series_id, season_number, episode_count, air_date, poster_path)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT(series_id, season_number) DO UPDATE SET
    episode_count = excluded.episode_count,
    air_date = excluded.air_date,
    poster_path   = excluded.poster_path
`

type UpsertSeasonParams struct {
	SeriesID     int64      `json:"series_id"`
	SeasonNumber int64      `json:"season_number"`
	EpisodeCount int64      `json:"episode_count"`
	AirDate      *time.Time `json:"air_date"`
	PosterPath   string     `json:"poster_path"`
}

func (q *Queries) UpsertSeason(ctx context.Context, arg UpsertSeasonParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertSeason,
		arg.SeriesID,
		arg.SeasonNumber,
		arg.EpisodeCount,
		arg.AirDate,
		arg.PosterPath,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
