// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
)

type Querier interface {
	GetMovies(ctx context.Context) ([]GetMoviesRow, error)
	GetOutOfSyncSeasons(ctx context.Context) ([]GetOutOfSyncSeasonsRow, error)
	GetOutOfSyncTVs(ctx context.Context) ([]GetOutOfSyncTVsRow, error)
	GetSeries(ctx context.Context) ([]GetSeriesRow, error)
	UpsertEpisode(ctx context.Context, arg UpsertEpisodeParams) (int64, error)
	UpsertMedia(ctx context.Context, arg UpsertMediaParams) (int64, error)
	UpsertSeason(ctx context.Context, arg UpsertSeasonParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
