// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CountEpisodes(ctx context.Context, arg CountEpisodesParams) (int64, error)
	GetMediaID(ctx context.Context, tmdbID int64) (int64, error)
	GetPendingEpisodes(ctx context.Context) ([]GetPendingEpisodesRow, error)
	GetSeasonID(ctx context.Context, arg GetSeasonIDParams) (int64, error)
	GetTVMedia(ctx context.Context) ([]GetTVMediaRow, error)
	MarkEpisodeDownloaded(ctx context.Context, id int64) error
	UpsertEpisode(ctx context.Context, arg UpsertEpisodeParams) (int64, error)
	UpsertMedia(ctx context.Context, arg UpsertMediaParams) (int64, error)
	UpsertSeason(ctx context.Context, arg UpsertSeasonParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
