// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package repo

import (
	"context"
	"time"
)

const getMoviePages = `-- name: GetMoviePages :many
SELECT 
  m.id,
  p.detail_path
FROM medias m
JOIN pages p
WHERE
  m.type = 'movie'
  AND m.status IN ('wanted', 'monitoring')
  AND p.provider = ?1
  AND p.media_id = m.id
  AND p.season_id IS NULL
`

type GetMoviePagesRow struct {
	ID         int64  `json:"id"`
	DetailPath string `json:"detail_path"`
}

func (q *Queries) GetMoviePages(ctx context.Context, provider string) ([]GetMoviePagesRow, error) {
	rows, err := q.db.QueryContext(ctx, getMoviePages, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMoviePagesRow
	for rows.Next() {
		var i GetMoviePagesRow
		if err := rows.Scan(&i.ID, &i.DetailPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMoviesWithoutPage = `-- name: GetMoviesWithoutPage :many
SELECT m.id, m.title, m.air_date
FROM medias m
WHERE m.type = 'movie'
  AND NOT EXISTS (
    SELECT 1
    FROM pages p
    WHERE p.provider = ?1
      AND p.media_id = m.id
      AND p.season_id IS NULL
  )
`

type GetMoviesWithoutPageRow struct {
	ID      int64     `json:"id"`
	Title   string    `json:"title"`
	AirDate time.Time `json:"air_date"`
}

func (q *Queries) GetMoviesWithoutPage(ctx context.Context, provider string) ([]GetMoviesWithoutPageRow, error) {
	rows, err := q.db.QueryContext(ctx, getMoviesWithoutPage, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMoviesWithoutPageRow
	for rows.Next() {
		var i GetMoviesWithoutPageRow
		if err := rows.Scan(&i.ID, &i.Title, &i.AirDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutOfSyncSeasons = `-- name: GetOutOfSyncSeasons :many
SELECT m.tmdb_id, s.id, s.season_number
FROM seasons s
JOIN medias m ON m.id = s.series_id
WHERE m.type IN ('tv', 'anime')
  AND m.status IN ('wanted', 'monitoring')
  AND s.episode_count > (
    SELECT COUNT(*) FROM episodes e WHERE e.season_id = s.id
  )
`

type GetOutOfSyncSeasonsRow struct {
	TmdbID       int64 `json:"tmdb_id"`
	ID           int64 `json:"id"`
	SeasonNumber int64 `json:"season_number"`
}

func (q *Queries) GetOutOfSyncSeasons(ctx context.Context) ([]GetOutOfSyncSeasonsRow, error) {
	rows, err := q.db.QueryContext(ctx, getOutOfSyncSeasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOutOfSyncSeasonsRow
	for rows.Next() {
		var i GetOutOfSyncSeasonsRow
		if err := rows.Scan(&i.TmdbID, &i.ID, &i.SeasonNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutOfSyncTVs = `-- name: GetOutOfSyncTVs :many
SELECT id, tmdb_id
FROM medias
WHERE type IN ('tv', 'anime')
  AND status IN ('wanted', 'monitoring')
`

type GetOutOfSyncTVsRow struct {
	ID     int64 `json:"id"`
	TmdbID int64 `json:"tmdb_id"`
}

func (q *Queries) GetOutOfSyncTVs(ctx context.Context) ([]GetOutOfSyncTVsRow, error) {
	rows, err := q.db.QueryContext(ctx, getOutOfSyncTVs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOutOfSyncTVsRow
	for rows.Next() {
		var i GetOutOfSyncTVsRow
		if err := rows.Scan(&i.ID, &i.TmdbID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeasonsWithoutPage = `-- name: GetSeasonsWithoutPage :many
SELECT 
  s.id AS season_id,
  s.series_id,
  m.type,
  m.title,
  s.air_date,
  s.season_number
FROM seasons s
JOIN medias m ON m.id = s.series_id
WHERE m.type IN ('tv', 'anime')
  AND NOT EXISTS (
    SELECT 1
    FROM pages p
    WHERE p.provider = ?1
      AND p.media_id = s.series_id
      AND p.season_id = s.id
  )
`

type GetSeasonsWithoutPageRow struct {
	SeasonID     int64     `json:"season_id"`
	SeriesID     int64     `json:"series_id"`
	Type         string    `json:"type"`
	Title        string    `json:"title"`
	AirDate      time.Time `json:"air_date"`
	SeasonNumber int64     `json:"season_number"`
}

func (q *Queries) GetSeasonsWithoutPage(ctx context.Context, provider string) ([]GetSeasonsWithoutPageRow, error) {
	rows, err := q.db.QueryContext(ctx, getSeasonsWithoutPage, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSeasonsWithoutPageRow
	for rows.Next() {
		var i GetSeasonsWithoutPageRow
		if err := rows.Scan(
			&i.SeasonID,
			&i.SeriesID,
			&i.Type,
			&i.Title,
			&i.AirDate,
			&i.SeasonNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEpisode = `-- name: UpsertEpisode :execrows
INSERT INTO episodes (season_id, episode_number, air_date)
VALUES (?1, ?2, ?3)
ON CONFLICT(season_id, episode_number) DO UPDATE SET
  air_date = excluded.air_date
`

type UpsertEpisodeParams struct {
	SeasonID      int64     `json:"season_id"`
	EpisodeNumber int64     `json:"episode_number"`
	AirDate       time.Time `json:"air_date"`
}

func (q *Queries) UpsertEpisode(ctx context.Context, arg UpsertEpisodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertEpisode, arg.SeasonID, arg.EpisodeNumber, arg.AirDate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertMedia = `-- name: UpsertMedia :execrows
INSERT INTO medias (tmdb_id, type, title, air_date, poster_path)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT(tmdb_id) DO UPDATE SET
  title = excluded.title,
  air_date = excluded.air_date,
  poster_path = excluded.poster_path
`

type UpsertMediaParams struct {
	TmdbID     int64     `json:"tmdb_id"`
	Type       string    `json:"type"`
	Title      string    `json:"title"`
	AirDate    time.Time `json:"air_date"`
	PosterPath string    `json:"poster_path"`
}

func (q *Queries) UpsertMedia(ctx context.Context, arg UpsertMediaParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertMedia,
		arg.TmdbID,
		arg.Type,
		arg.Title,
		arg.AirDate,
		arg.PosterPath,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertPages = `-- name: UpsertPages :execrows
INSERT INTO pages (provider, media_id, season_id, detail_path)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT(provider, detail_path) DO NOTHING
`

type UpsertPagesParams struct {
	Provider   string `json:"provider"`
	MediaID    int64  `json:"media_id"`
	SeasonID   *int64 `json:"season_id"`
	DetailPath string `json:"detail_path"`
}

func (q *Queries) UpsertPages(ctx context.Context, arg UpsertPagesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertPages,
		arg.Provider,
		arg.MediaID,
		arg.SeasonID,
		arg.DetailPath,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertSeason = `-- name: UpsertSeason :execrows
INSERT INTO seasons (series_id, season_number, episode_count, air_date, poster_path)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT(series_id, season_number) DO UPDATE SET
  episode_count = excluded.episode_count,
  air_date = excluded.air_date,
  poster_path = excluded.poster_path
`

type UpsertSeasonParams struct {
	SeriesID     int64     `json:"series_id"`
	SeasonNumber int64     `json:"season_number"`
	EpisodeCount int64     `json:"episode_count"`
	AirDate      time.Time `json:"air_date"`
	PosterPath   string    `json:"poster_path"`
}

func (q *Queries) UpsertSeason(ctx context.Context, arg UpsertSeasonParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertSeason,
		arg.SeriesID,
		arg.SeasonNumber,
		arg.EpisodeCount,
		arg.AirDate,
		arg.PosterPath,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
