// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: server.sql

package repo

import (
	"context"
)

const getEpisodes = `-- name: GetEpisodes :many
SELECT id, season_id, episode_number, air_date, status
FROM episodes
WHERE season_id = ?1
`

func (q *Queries) GetEpisodes(ctx context.Context, seasonID int64) ([]Episode, error) {
	rows, err := q.db.QueryContext(ctx, getEpisodes, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.SeasonID,
			&i.EpisodeNumber,
			&i.AirDate,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMedias = `-- name: GetMedias :many
SELECT id, tmdb_id, type, title, air_date, poster_path, status FROM medias
`

func (q *Queries) GetMedias(ctx context.Context) ([]Media, error) {
	rows, err := q.db.QueryContext(ctx, getMedias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Media
	for rows.Next() {
		var i Media
		if err := rows.Scan(
			&i.ID,
			&i.TmdbID,
			&i.Type,
			&i.Title,
			&i.AirDate,
			&i.PosterPath,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeasons = `-- name: GetSeasons :many
SELECT id, series_id, season_number, episode_count, air_date, poster_path
FROM seasons
WHERE series_id = ?1
`

func (q *Queries) GetSeasons(ctx context.Context, seriesID int64) ([]Season, error) {
	rows, err := q.db.QueryContext(ctx, getSeasons, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Season
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.SeasonNumber,
			&i.EpisodeCount,
			&i.AirDate,
			&i.PosterPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
