// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package repo

import (
	"context"
	"time"
)

const createDownload = `-- name: CreateDownload :execrows
INSERT INTO downloads (magnet_id)
SELECT ?1
WHERE NOT EXISTS (
  SELECT 1
  FROM downloads
  WHERE magnet_id = ?1
    AND status IN ('queued', 'downloading')
)
`

func (q *Queries) CreateDownload(ctx context.Context, magnetID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, createDownload, magnetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBestMagnetOfMovie = `-- name: GetBestMagnetOfMovie :one
SELECT
  m.id,
  m.magnet_url
FROM magnets m
LEFT JOIN profile_priorities pp
  ON pp.profile = m.profile
WHERE
  m.media_id = ?1
  AND m.size_mb >= ?2
  AND m.size_mb <= ?3
  AND m.season_id IS NULL
  AND m.status = 'available'
ORDER BY
  pp.priority IS NULL,
  pp.priority ASC,
  m.seeder DESC,
  m.size_mb DESC
LIMIT 1
`

type GetBestMagnetOfMovieParams struct {
	MediaID   int64   `json:"media_id"`
	MinSizeMb float64 `json:"min_size_mb"`
	MaxSizeMb float64 `json:"max_size_mb"`
}

type GetBestMagnetOfMovieRow struct {
	ID        int64  `json:"id"`
	MagnetUrl string `json:"magnet_url"`
}

func (q *Queries) GetBestMagnetOfMovie(ctx context.Context, arg GetBestMagnetOfMovieParams) (GetBestMagnetOfMovieRow, error) {
	row := q.db.QueryRowContext(ctx, getBestMagnetOfMovie, arg.MediaID, arg.MinSizeMb, arg.MaxSizeMb)
	var i GetBestMagnetOfMovieRow
	err := row.Scan(&i.ID, &i.MagnetUrl)
	return i, err
}

const getMoviePages = `-- name: GetMoviePages :many
SELECT 
  m.id AS media_id,
  p.detail_path
FROM medias m
JOIN pages p ON p.media_id = m.id
WHERE
  m.type = 'movie'
  AND m.status IN ('wanted', 'monitoring')
  AND p.provider = ?1
  AND p.season_id IS NULL
`

type GetMoviePagesRow struct {
	MediaID    int64  `json:"media_id"`
	DetailPath string `json:"detail_path"`
}

func (q *Queries) GetMoviePages(ctx context.Context, provider string) ([]GetMoviePagesRow, error) {
	rows, err := q.db.QueryContext(ctx, getMoviePages, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMoviePagesRow
	for rows.Next() {
		var i GetMoviePagesRow
		if err := rows.Scan(&i.MediaID, &i.DetailPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMoviesWithoutPage = `-- name: GetMoviesWithoutPage :many
SELECT m.id, m.title, m.air_date
FROM medias m
WHERE m.type = 'movie'
  AND NOT EXISTS (
    SELECT 1
    FROM pages p
    WHERE p.provider = ?1
      AND p.media_id = m.id
      AND p.season_id IS NULL
  )
`

type GetMoviesWithoutPageRow struct {
	ID      int64     `json:"id"`
	Title   string    `json:"title"`
	AirDate time.Time `json:"air_date"`
}

func (q *Queries) GetMoviesWithoutPage(ctx context.Context, provider string) ([]GetMoviesWithoutPageRow, error) {
	rows, err := q.db.QueryContext(ctx, getMoviesWithoutPage, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMoviesWithoutPageRow
	for rows.Next() {
		var i GetMoviesWithoutPageRow
		if err := rows.Scan(&i.ID, &i.Title, &i.AirDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutOfSyncSeasons = `-- name: GetOutOfSyncSeasons :many
SELECT m.tmdb_id, s.id, s.season_number
FROM seasons s
JOIN medias m ON m.id = s.series_id
WHERE m.type IN ('tv', 'anime')
  AND m.status IN ('wanted', 'monitoring')
  AND s.episode_count > (
    SELECT COUNT(*) FROM episodes e WHERE e.season_id = s.id
  )
`

type GetOutOfSyncSeasonsRow struct {
	TmdbID       int64 `json:"tmdb_id"`
	ID           int64 `json:"id"`
	SeasonNumber int64 `json:"season_number"`
}

func (q *Queries) GetOutOfSyncSeasons(ctx context.Context) ([]GetOutOfSyncSeasonsRow, error) {
	rows, err := q.db.QueryContext(ctx, getOutOfSyncSeasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOutOfSyncSeasonsRow
	for rows.Next() {
		var i GetOutOfSyncSeasonsRow
		if err := rows.Scan(&i.TmdbID, &i.ID, &i.SeasonNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutOfSyncTVs = `-- name: GetOutOfSyncTVs :many
SELECT id, tmdb_id
FROM medias
WHERE type IN ('tv', 'anime')
  AND status IN ('wanted', 'monitoring')
`

type GetOutOfSyncTVsRow struct {
	ID     int64 `json:"id"`
	TmdbID int64 `json:"tmdb_id"`
}

func (q *Queries) GetOutOfSyncTVs(ctx context.Context) ([]GetOutOfSyncTVsRow, error) {
	rows, err := q.db.QueryContext(ctx, getOutOfSyncTVs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOutOfSyncTVsRow
	for rows.Next() {
		var i GetOutOfSyncTVsRow
		if err := rows.Scan(&i.ID, &i.TmdbID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingMovies = `-- name: GetPendingMovies :many
SELECT id
FROM medias
WHERE type = 'movie'
  AND status IN ('wanted', 'monitoring')
`

func (q *Queries) GetPendingMovies(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getPendingMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQueuedDownloads = `-- name: GetQueuedDownloads :many
SELECT
  d.id,
  d.magnet_id,
  m.magnet_url
FROM downloads d
JOIN magnets m ON m.id = d.magnet_id
WHERE d.status = 'queued'
`

type GetQueuedDownloadsRow struct {
	ID        int64  `json:"id"`
	MagnetID  int64  `json:"magnet_id"`
	MagnetUrl string `json:"magnet_url"`
}

func (q *Queries) GetQueuedDownloads(ctx context.Context) ([]GetQueuedDownloadsRow, error) {
	rows, err := q.db.QueryContext(ctx, getQueuedDownloads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQueuedDownloadsRow
	for rows.Next() {
		var i GetQueuedDownloadsRow
		if err := rows.Scan(&i.ID, &i.MagnetID, &i.MagnetUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeasonDownloadStats = `-- name: GetSeasonDownloadStats :many
SELECT
  s.id AS season_id,
  COUNT(e.id) AS total_count,
  COUNT(CASE WHEN e.status = 'pending' THEN 1 END) AS missing_count
FROM episodes e
JOIN seasons s ON s.id = e.season_id
JOIN medias m ON m.id = s.series_id
WHERE m.type IN ('tv', 'anime')
  AND m.status IN ('wanted', 'monitoring')
GROUP BY s.id
HAVING COUNT(CASE WHEN e.status = 'pending' THEN 1 END) > 0
`

type GetSeasonDownloadStatsRow struct {
	SeasonID     int64 `json:"season_id"`
	TotalCount   int64 `json:"total_count"`
	MissingCount int64 `json:"missing_count"`
}

func (q *Queries) GetSeasonDownloadStats(ctx context.Context) ([]GetSeasonDownloadStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSeasonDownloadStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSeasonDownloadStatsRow
	for rows.Next() {
		var i GetSeasonDownloadStatsRow
		if err := rows.Scan(&i.SeasonID, &i.TotalCount, &i.MissingCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeasonMagnetCandidates = `-- name: GetSeasonMagnetCandidates :many
SELECT
  m.id,
  m.magnet_url,
  m.seeder,
  COUNT(me.episode_id) AS total_cover_count,
  COUNT(CASE WHEN e.status = 'pending' THEN 1 END) AS missing_hit_count,
  COUNT(CASE WHEN e.status IN ('downloading', 'downloaded') THEN 1 END) AS extra_count,
  COALESCE(pp.priority, 999999) AS profile_priority
FROM magnets m
JOIN magnet_episodes me ON me.magnet_id = m.id
JOIN episodes e ON e.id = me.episode_id
LEFT JOIN profile_priorities pp
  ON pp.profile = m.profile
WHERE
  m.season_id = ?1
  AND m.status = 'available'
GROUP BY m.id
HAVING COUNT(CASE WHEN e.status = 'pending' THEN 1 END) > 0
`

type GetSeasonMagnetCandidatesRow struct {
	ID              int64  `json:"id"`
	MagnetUrl       string `json:"magnet_url"`
	Seeder          int64  `json:"seeder"`
	TotalCoverCount int64  `json:"total_cover_count"`
	MissingHitCount int64  `json:"missing_hit_count"`
	ExtraCount      int64  `json:"extra_count"`
	ProfilePriority int64  `json:"profile_priority"`
}

func (q *Queries) GetSeasonMagnetCandidates(ctx context.Context, seasonID *int64) ([]GetSeasonMagnetCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, getSeasonMagnetCandidates, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSeasonMagnetCandidatesRow
	for rows.Next() {
		var i GetSeasonMagnetCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.MagnetUrl,
			&i.Seeder,
			&i.TotalCoverCount,
			&i.MissingHitCount,
			&i.ExtraCount,
			&i.ProfilePriority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeasonPages = `-- name: GetSeasonPages :many
SELECT
  s.id AS season_id,
  s.series_id AS media_id,
  s.episode_count,
  p.detail_path
FROM seasons s
JOIN medias m ON m.id = s.series_id
JOIN pages p
  ON p.media_id = s.series_id
  AND p.season_id = s.id
WHERE
  m.type IN ('tv', 'anime')
  AND m.status IN ('wanted', 'monitoring')
  AND p.provider = ?1
`

type GetSeasonPagesRow struct {
	SeasonID     int64  `json:"season_id"`
	MediaID      int64  `json:"media_id"`
	EpisodeCount int64  `json:"episode_count"`
	DetailPath   string `json:"detail_path"`
}

func (q *Queries) GetSeasonPages(ctx context.Context, provider string) ([]GetSeasonPagesRow, error) {
	rows, err := q.db.QueryContext(ctx, getSeasonPages, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSeasonPagesRow
	for rows.Next() {
		var i GetSeasonPagesRow
		if err := rows.Scan(
			&i.SeasonID,
			&i.MediaID,
			&i.EpisodeCount,
			&i.DetailPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeasonsWithoutPage = `-- name: GetSeasonsWithoutPage :many
SELECT 
  s.id AS season_id,
  s.series_id,
  m.type,
  m.title,
  s.air_date,
  s.season_number
FROM seasons s
JOIN medias m ON m.id = s.series_id
WHERE m.type IN ('tv', 'anime')
  AND NOT EXISTS (
    SELECT 1
    FROM pages p
    WHERE p.provider = ?1
      AND p.media_id = s.series_id
      AND p.season_id = s.id
  )
`

type GetSeasonsWithoutPageRow struct {
	SeasonID     int64     `json:"season_id"`
	SeriesID     int64     `json:"series_id"`
	Type         string    `json:"type"`
	Title        string    `json:"title"`
	AirDate      time.Time `json:"air_date"`
	SeasonNumber int64     `json:"season_number"`
}

func (q *Queries) GetSeasonsWithoutPage(ctx context.Context, provider string) ([]GetSeasonsWithoutPageRow, error) {
	rows, err := q.db.QueryContext(ctx, getSeasonsWithoutPage, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSeasonsWithoutPageRow
	for rows.Next() {
		var i GetSeasonsWithoutPageRow
		if err := rows.Scan(
			&i.SeasonID,
			&i.SeriesID,
			&i.Type,
			&i.Title,
			&i.AirDate,
			&i.SeasonNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDownloadCompleted = `-- name: MarkDownloadCompleted :execrows
UPDATE downloads
SET status = 'completed'
WHERE id = ?1
`

func (q *Queries) MarkDownloadCompleted(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, markDownloadCompleted, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markDownloadFailed = `-- name: MarkDownloadFailed :execrows
UPDATE downloads
SET
  status = 'failed',
  error = ?2
WHERE id = ?1
`

type MarkDownloadFailedParams struct {
	ID    int64   `json:"id"`
	Error *string `json:"error"`
}

func (q *Queries) MarkDownloadFailed(ctx context.Context, arg MarkDownloadFailedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markDownloadFailed, arg.ID, arg.Error)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markDownloadStarted = `-- name: MarkDownloadStarted :execrows
UPDATE downloads
SET
  qb_hash = ?2,
  status = 'downloading',
  error = NULL
WHERE id = ?1
`

type MarkDownloadStartedParams struct {
	ID     int64   `json:"id"`
	QbHash *string `json:"qb_hash"`
}

func (q *Queries) MarkDownloadStarted(ctx context.Context, arg MarkDownloadStartedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markDownloadStarted, arg.ID, arg.QbHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markEpisodesDownloadedByMagnet = `-- name: MarkEpisodesDownloadedByMagnet :execrows
UPDATE episodes
SET status = 'downloaded'
WHERE id IN (
  SELECT episode_id
  FROM magnet_episodes
  WHERE magnet_id = ?1
)
`

func (q *Queries) MarkEpisodesDownloadedByMagnet(ctx context.Context, magnetID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, markEpisodesDownloadedByMagnet, magnetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markEpisodesDownloadingByMagnet = `-- name: MarkEpisodesDownloadingByMagnet :execrows
UPDATE episodes
SET status = 'downloading'
WHERE id IN (
  SELECT episode_id
  FROM magnet_episodes
  WHERE magnet_id = ?1
)
  AND status = 'pending'
`

func (q *Queries) MarkEpisodesDownloadingByMagnet(ctx context.Context, magnetID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, markEpisodesDownloadingByMagnet, magnetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markMovieCompletedByMagnet = `-- name: MarkMovieCompletedByMagnet :execrows
UPDATE medias
SET status = 'completed'
WHERE id = (
  SELECT media_id
  FROM magnets m
  WHERE m.id = ?1
)
  AND type = 'movie'
`

func (q *Queries) MarkMovieCompletedByMagnet(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, markMovieCompletedByMagnet, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markMovieDownloadingByMagnet = `-- name: MarkMovieDownloadingByMagnet :execrows
UPDATE medias
SET status = 'downloading'
WHERE id = (
  SELECT media_id
  FROM magnets m
  WHERE m.id = ?1
)
  AND type = 'movie'
  AND status IN ('wanted', 'monitoring')
`

func (q *Queries) MarkMovieDownloadingByMagnet(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, markMovieDownloadingByMagnet, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertEpisode = `-- name: UpsertEpisode :execrows
INSERT INTO episodes (season_id, episode_number, air_date)
VALUES (?1, ?2, ?3)
ON CONFLICT(season_id, episode_number) DO UPDATE SET
  air_date = excluded.air_date
`

type UpsertEpisodeParams struct {
	SeasonID      int64     `json:"season_id"`
	EpisodeNumber int64     `json:"episode_number"`
	AirDate       time.Time `json:"air_date"`
}

func (q *Queries) UpsertEpisode(ctx context.Context, arg UpsertEpisodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertEpisode, arg.SeasonID, arg.EpisodeNumber, arg.AirDate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertMagnetEpisodeByEpisodeNumber = `-- name: UpsertMagnetEpisodeByEpisodeNumber :execrows
INSERT INTO magnet_episodes (magnet_id, episode_id)
SELECT
  ?1,
  e.id
FROM episodes e
WHERE
  e.season_id = ?2
  AND e.episode_number = ?3
ON CONFLICT(magnet_id, episode_id) DO NOTHING
`

type UpsertMagnetEpisodeByEpisodeNumberParams struct {
	MagnetID      int64 `json:"magnet_id"`
	SeasonID      int64 `json:"season_id"`
	EpisodeNumber int64 `json:"episode_number"`
}

func (q *Queries) UpsertMagnetEpisodeByEpisodeNumber(ctx context.Context, arg UpsertMagnetEpisodeByEpisodeNumberParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertMagnetEpisodeByEpisodeNumber, arg.MagnetID, arg.SeasonID, arg.EpisodeNumber)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertMagnetEpisodeBySeasonID = `-- name: UpsertMagnetEpisodeBySeasonID :execrows
INSERT INTO magnet_episodes (magnet_id, episode_id)
SELECT
  ?1,
  e.id
FROM episodes e
WHERE
  e.season_id = ?2
ON CONFLICT(magnet_id, episode_id) DO NOTHING
`

type UpsertMagnetEpisodeBySeasonIDParams struct {
	MagnetID int64 `json:"magnet_id"`
	SeasonID int64 `json:"season_id"`
}

func (q *Queries) UpsertMagnetEpisodeBySeasonID(ctx context.Context, arg UpsertMagnetEpisodeBySeasonIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertMagnetEpisodeBySeasonID, arg.MagnetID, arg.SeasonID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertMagnets = `-- name: UpsertMagnets :one
INSERT INTO magnets (
  media_id, 
  season_id, 
  title, 
  magnet_url,
  size_mb,
  seeder,
  profile
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7
)
ON CONFLICT(magnet_url) DO UPDATE SET
  title = excluded.title,
  size_mb = excluded.size_mb,
  seeder = excluded.seeder,
  profile = excluded.profile
RETURNING id
`

type UpsertMagnetsParams struct {
	MediaID   int64   `json:"media_id"`
	SeasonID  *int64  `json:"season_id"`
	Title     string  `json:"title"`
	MagnetUrl string  `json:"magnet_url"`
	SizeMb    float64 `json:"size_mb"`
	Seeder    int64   `json:"seeder"`
	Profile   string  `json:"profile"`
}

func (q *Queries) UpsertMagnets(ctx context.Context, arg UpsertMagnetsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertMagnets,
		arg.MediaID,
		arg.SeasonID,
		arg.Title,
		arg.MagnetUrl,
		arg.SizeMb,
		arg.Seeder,
		arg.Profile,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertMedia = `-- name: UpsertMedia :execrows
INSERT INTO medias (tmdb_id, type, title, air_date, poster_path)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT(tmdb_id, type) DO UPDATE SET
  title = excluded.title,
  air_date = excluded.air_date,
  poster_path = excluded.poster_path
`

type UpsertMediaParams struct {
	TmdbID     int64     `json:"tmdb_id"`
	Type       string    `json:"type"`
	Title      string    `json:"title"`
	AirDate    time.Time `json:"air_date"`
	PosterPath string    `json:"poster_path"`
}

func (q *Queries) UpsertMedia(ctx context.Context, arg UpsertMediaParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertMedia,
		arg.TmdbID,
		arg.Type,
		arg.Title,
		arg.AirDate,
		arg.PosterPath,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertPages = `-- name: UpsertPages :execrows
INSERT INTO pages (provider, media_id, season_id, detail_path)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT(provider, detail_path) DO NOTHING
`

type UpsertPagesParams struct {
	Provider   string `json:"provider"`
	MediaID    int64  `json:"media_id"`
	SeasonID   *int64 `json:"season_id"`
	DetailPath string `json:"detail_path"`
}

func (q *Queries) UpsertPages(ctx context.Context, arg UpsertPagesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertPages,
		arg.Provider,
		arg.MediaID,
		arg.SeasonID,
		arg.DetailPath,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertProfilePriority = `-- name: UpsertProfilePriority :execrows
INSERT INTO profile_priorities (profile, priority)
VALUES (?1, ?2)
ON CONFLICT(profile) DO UPDATE SET
  priority = excluded.priority
`

type UpsertProfilePriorityParams struct {
	Profile  string `json:"profile"`
	Priority int64  `json:"priority"`
}

func (q *Queries) UpsertProfilePriority(ctx context.Context, arg UpsertProfilePriorityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertProfilePriority, arg.Profile, arg.Priority)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertSeason = `-- name: UpsertSeason :execrows
INSERT INTO seasons (series_id, season_number, episode_count, air_date, poster_path)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT(series_id, season_number) DO UPDATE SET
  episode_count = excluded.episode_count,
  air_date = excluded.air_date,
  poster_path = excluded.poster_path
`

type UpsertSeasonParams struct {
	SeriesID     int64     `json:"series_id"`
	SeasonNumber int64     `json:"season_number"`
	EpisodeCount int64     `json:"episode_count"`
	AirDate      time.Time `json:"air_date"`
	PosterPath   string    `json:"poster_path"`
}

func (q *Queries) UpsertSeason(ctx context.Context, arg UpsertSeasonParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertSeason,
		arg.SeriesID,
		arg.SeasonNumber,
		arg.EpisodeCount,
		arg.AirDate,
		arg.PosterPath,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
